#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

 wget -O discord.deb "https://discordapp.com/api/download?platform=linux&format=deb"

sudo apt install -f

sudo dpkg -i /home/pi/discord.deb

exit 0




