#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

wget -O virtualcode.deb "https://go.microsoft.com/fwlink/?LinkID=760868"

sudo apt install -f

sudo dpkg -i /home/pi/virtualcode.deb

exit 0